In [1]:
import ydf
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

# 1. EDA

In [2]:
df = pd.read_csv("1 - Project Data.csv")

In [3]:
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,Competitor had better devices

In [4]:
df.isna().sum()

CustomerID              0
Count                   0
Country                 0
State                   0
City                    0
Zip Code                0
Lat Long                0
Latitude                0
Longitude               0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges           0
Churn Label             0
Churn Value             0
Churn Reason         5174
dtype: int64

In [6]:
df['Churn Value'].value_counts(normalize=True)

Churn Value
0    0.73463
1    0.26537
Name: proportion, dtype: float64

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 31 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   str
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   str
 3   State              7043 non-null   str
 4   City               7043 non-null   str
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   str
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   str
 10  Senior Citizen     7043 non-null   str
 11  Partner            7043 non-null   str
 12  Dependents         7043 non-null   str
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   str
 15  Multiple Lines     7043 non-null   str
 16  Internet Service   7043 non-null   str
 17  Online Security    7043 non-null   str
 18  Online Backup      7043 non-null   str
 19  Device Protection  7043 non-null   str
 20  Tech Support       7043 non-null   str
 21  Streaming TV       7043 non-null   str
 22  Streaming Movies   7043 non-null   str
 23  Contract           7043 non-null   str
 24  Paperless Billing  7043 non-null   str
 25  Payment Method     7043 non-null   str
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   str
 28  Churn Label        7043 non-null   str
 29  Churn Value        7043 non-null   int64
 30  Churn Reason       1869 non-null   str
dtypes: float64(3), int64(4), str(24)
memory usage: 2.8 MB

In [ ]:
df

0     108.15
1     151.65
2      820.5
3    3046.05
4     5036.3
Name: Total Charges, dtype: str

In [10]:
df.shape

(7043, 31)

# 2. Cleaning

In [11]:
df_clean = df.copy()

In [12]:
df_clean['Total Charges'] = pd.to_numeric(df_clean['Total Charges'], errors='coerce').fillna(0.0)

In [13]:
addons = ['Online Security', 'Online Backup', 'Device Protection',
          'Tech Support', 'Streaming TV', 'Streaming Movies']
df_clean[addons] = df_clean[addons].replace('No internet service', 'No')
df_clean['Multiple Lines'] = df_clean['Multiple Lines'].replace('No phone service', 'No')

# 3. Feature Engineering

In [14]:
DROPS = [
    "Count", "Country", "State",
    "CustomerID",
    "Churn Label", "Churn Value",
    "Churn Reason",
    "Lat Long",
    "City", "Zip Code", "Latitude", "Longitude",
    "Total Charges",
]

customer_ids = df_clean["CustomerID"]
y = df_clean["Churn Value"]
X = df_clean.drop(columns=DROPS)

In [15]:
X_enc = pd.get_dummies(X, drop_first=True, dtype=int)
FEATURE_COLUMNS = list(X_enc.columns)

In [16]:
X_enc.head()

,Tenure Months,Monthly Charges,Gender_Male,Senior Citizen_Yes,Partner_Yes,Dependents_Yes,Phone Service_Yes,Multiple Lines_Yes,Internet Service_Fiber optic,Internet Service_No,...,Device Protection_Yes,Tech Support_Yes,Streaming TV_Yes,Streaming Movies_Yes,Contract_One year,Contract_Two year,Paperless Billing_Yes,Payment Method_Credit card (automatic),Payment Method_Electronic check,Payment Method_Mailed check
0,2,53.85,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,1
1,2,70.70,0,0,0,1,1,0,1,0,...,0,0,0,0,0,0,1,0,1,0
2,8,99.65,0,0,0,1,1,1,1,0,...,1,0,1,1,0,0,1,0,1,0
3,28,104.80,0,0,1,1,1,1,1,0,...,1,1,1,1,0,0,1,0,1,0
4,49,103.70,1,0,0,1,1,1,1,0,...,1,0,1,1,0,0,1,0,0,0